apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.codegeek.com
spec:
  group: codegeek.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
                  description: "URL of the website to fetch and serve"
              required:
                - website_url
            status:
              type: object
              properties:
                state:
                  type: string
                  description: "Current state of the DummySite"
                url:
                  type: string
                  description: "URL where the site is accessible"
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: dummysites
    singular: dummysite
    kind: DummySite
    shortNames:
      - ds