apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: logtext
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: ping-pong
          image: usmanusman/pingpong:v3
          volumeMounts:
            - name: logtext
              mountPath: /usr/src/app/files
          env:
          - name: PORT
            value: "4000"
          - name: FILE_PATH
            value: "/usr/src/app/files/pingtext"