---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: exercises
  name: ping-pong-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: logtext
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: ping-pong
          image: usmanusman/pingpong:v7
          volumeMounts:
            - name: logtext
              mountPath: /usr/src/app/files
          env:
          - name: PORT
            value: "4000"
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres@postgres-service:5432/postgres?sslmode=disable"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {duration: 2m}
        - setWeight: 100
      analysis:
        templates:
          - templateName: cpu-usage-analysis
        startingStep: 1
        args:
          - name: namespace
            value: exercises

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  namespace: exercises
  name: cpu-usage-analysis
spec:
  args:
    - name: namespace
  metrics:
    - name: cpu-usage-rate
      initialDelay: 1m
      interval: 1m
      count: 5
      successCondition: result < 0.8
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-stack-1759-prometheus-0.prometheus.svc.cluster.local:9090
          query: |
            sum(rate(container_cpu_usage_seconds_total{namespace="{{args.namespace}}"}[5m]))