apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 4000