apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/deployment-app.yaml
  - manifests/deployment-backend.yaml
  - manifests/deployment-broadcaster.yaml
  - manifests/service-app.yaml
  - manifests/service-backend.yaml
  - manifests/ingress.yaml
  - manifests/psql-stateful.yaml
  - manifests/reminder-cron.yaml
  # - pg-backup/db-backup-cron.yaml

images:
  - name: todoapp
    newName: usmanusman/todoapp:v3
  - name: todo-backend
    newName: usmanusman/todo-backend:v6
  - name: broadcaster
    newName: usmanusman/broadcaster:v6
