apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment-app.yaml
  - manifests/deployment-backend.yaml
  - manifests/ingress.yaml
  - manifests/psql-stateful.yaml
  - manifests/reminder-cron.yaml
  - manifests/service-backend.yaml
  - manifests/service-app.yaml
