apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
  namespace: exercises
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 100Mi
