---
# ConfigMap definition
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
data:
  # File content that will be mounted as information.txt
  information.txt: |
    this text is from file
  # Environment variable
  MESSAGE: "hello world"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim-logoutput
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 100Mi


---
# Updated Deployment with ConfigMap integration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: logtext
          persistentVolumeClaim:
            claimName: log-claim-logoutput
        # New volume for ConfigMap file
        - name: config-volume
          configMap:
            name: log-output-config
            items:
            - key: information.txt
              path: information.txt
      containers:
        - name: log-output-api
          image: usmanusman/logoutput-api:v8
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: logtext
              mountPath: /usr/src/app/files
            # Mount ConfigMap file
            - name: config-volume
              mountPath: /usr/src/app/config
              readOnly: true
          env:
            - name: PORT
              value: "4000"
            - name: LOG_PATH
              value: "/usr/src/app/files/logtext"
            # Environment variable from ConfigMap
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
            # Path to the config file
            - name: CONFIG_FILE_PATH
              value: "/usr/src/app/config/information.txt"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
        - name: log-output-generator
          image: usmanusman/logoutput-generator:v2
          volumeMounts:
            - name: logtext
              mountPath: /usr/src/app/files
          env:
            - name: FILE_PATH
              value: "/usr/src/app/files/logtext"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v1
  labels:
    app: greeter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
      - name: greeter
        image: usmanusman/greeter
        ports:
        - containerPort: 4000
        env:
        - name: VERSION
          value: "1"
        - name: PORT
          value: "4000"
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v2
  labels:
    app: greeter
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v2
  template:
    metadata:
      labels:
        app: greeter
        version: v2
    spec:
      containers:
      - name: greeter
        image: usmanusman/greeter
        ports:
        - containerPort: 4000
        env:
        - name: VERSION
          value: "2"
        - name: PORT
          value: "4000"
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5