apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: logtext
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: log-output-api
          image: usmanusman/logoutput-api:v3
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: logtext
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "4000"
            - name: LOG_PATH
              value: "/usr/src/app/files/logtext"
            # - name: PING_PATH
            #   value: "/usr/src/app/files/pingtext"

        - name: log-output-generator
          image: usmanusman/logoutput-generator:v2
          volumeMounts:
            - name: logtext
              mountPath: /usr/src/app/files
          env:
            - name: FILE_PATH
              value: "/usr/src/app/files/logtext"
