apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: logoutput-httproute
spec:
  parentRefs:
  - name: logoutput-gateway
    kind: Gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: logoutput-svc
      port: 80