apiVersion: v1
kind: Service
metadata:
  name: logoutput-svc
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: greeter-svc
  labels:
    app: greeter
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: greeter-v1-svc
  labels:
    app: greeter
    version: v1
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v1
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: greeter-v2-svc
  labels:
    app: greeter
    version: v2
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v2
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP