apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: picsum-image
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: todoapp
          image: usmanusman/todoapp:v1
          volumeMounts:
            - name: picsum-image
              mountPath: /usr/src/app/files
          env:
          - name: PORT
            value: "4000"
          - name: STATIC_PATH
            value: "/usr/src/app/files/static"