apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: db-url
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wb3N0Z3Jlcz9zc2xtb2RlPWRpc2FibGU=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: tod-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todoapp
          image: usmanusman/todo-backend:v3
          env:
          - name: PORT
            value: "4000"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url
                key: DATABASE_URL