apiVersion: apps/v1
kind: Deployment
metadata:
  name: tod-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todoapp
          image: usmanusman/todo-backend:v1
          env:
          - name: PORT
            value: "4000"