name: Release application

on:
  push:
    paths:
      - 'todoapp/**'
      - '.github/workflows/**'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repo
  BRANCH: ${{ github.ref_name }}

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      todo-app: ${{ steps.filter.outputs.todo-app }}
      todo-backend: ${{ steps.filter.outputs.todo-backend }}
      log-output: ${{ steps.filter.outputs.log-output }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            todo-app:
              - 'todoapp/todo-app/**'
              - 'todoapp/manifests/deployment-app.yaml'
            todo-backend:
              - 'todoapp/todo-backend/**'
              - 'todoapp/manifests/deployment-backend.yaml'
            log-output:
              - 'log_output/log_output_api/**'

  
  build-log-output:
    name: Build and Push log-output
    needs: detect-changes
    if: needs.detect-changes.outputs.log-output == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - run: gcloud --quiet auth configure-docker ${{ env.REGISTRY }}

      - name: 'Build and Push log-output'
        run: |
          IMAGE_TAG=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/log-output:${{ env.BRANCH }}-${{ github.sha }}
          docker build --tag $IMAGE_TAG ./log_output/log_output_api
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |
          cd ./log_output
          kustomize edit set image PROJECT/IMAGE=$IMAGE_TAG

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: './log_output/kustomization.yaml'
          message: New version released ${{ github.sha }}

  build-todo-app:
    name: Build and Deploy Todo App
    needs: detect-changes
    if: needs.detect-changes.outputs.todo-app == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - run: gcloud --quiet auth configure-docker ${{ env.REGISTRY }}
    
      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Set environment namespace'
        run: |
          if [ "${{ env.BRANCH }}" = "main" ]; then
            echo "NAMESPACE=project" >> $GITHUB_ENV
          else
            echo "NAMESPACE=${{ env.BRANCH }}" >> $GITHUB_ENV
          fi

      - name: 'Build and Push Todo App'
        run: |
          IMAGE_TAG=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/todo-app:${{ env.BRANCH }}-${{ github.sha }}
          docker build --tag $IMAGE_TAG ./todoapp/todo-app
          docker push $IMAGE_TAG
          echo "TODO_APP_IMAGE=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy Todo App with Kustomize
        working-directory: ./todoapp
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} || true
          kubectl config set-context --current --namespace=${{ env.NAMESPACE }}
          kustomize edit set namespace ${{ env.NAMESPACE }}
          kustomize edit set image todo-app=${{ env.TODO_APP_IMAGE }}
          kustomize build . | kubectl apply -f - --server-side --force-conflicts
          kubectl rollout status deployment/todoapp-dep -n ${{ env.NAMESPACE }}
          kubectl get services -o wide -n ${{ env.NAMESPACE }}

  build-todo-backend:
    name: Build and Deploy Todo Backend
    needs: detect-changes
    if: needs.detect-changes.outputs.todo-backend == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - run: gcloud --quiet auth configure-docker ${{ env.REGISTRY }}
    
      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Set environment namespace'
        run: |
          if [ "${{ env.BRANCH }}" = "main" ]; then
            echo "NAMESPACE=project" >> $GITHUB_ENV
          else
            echo "NAMESPACE=${{ env.BRANCH }}" >> $GITHUB_ENV
          fi

      - name: 'Build and Push Todo Backend'
        run: |
          IMAGE_TAG=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/todo-backend:${{ env.BRANCH }}-${{ github.sha }}
          docker build --tag $IMAGE_TAG ./todoapp/todo-backend
          docker push $IMAGE_TAG
          echo "TODO_BACKEND_IMAGE=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy Todo Backend with Kustomize
        working-directory: ./todoapp
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} || true
          kubectl config set-context --current --namespace=${{ env.NAMESPACE }}
          kustomize edit set namespace ${{ env.NAMESPACE }}
          kustomize edit set image todo-backend=${{ env.TODO_BACKEND_IMAGE }}
          kustomize build . | kubectl apply -f - --server-side --force-conflicts
          kubectl rollout status deployment/todo-backend-dep -n ${{ env.NAMESPACE }}
          kubectl get services -o wide -n ${{ env.NAMESPACE }}